import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default function AboutSection() {
  return (
    <section id="about" className="py-16 bg-blue-50  w-full flex justify-center items-center">
      <div className="container">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tight mb-4">About Image Regeneration</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Understanding the technology behind image regeneration using Autoencoders and Variational Autoencoders
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          <Card>
            <CardHeader>
              <CardTitle>Autoencoders (AE)</CardTitle>
              <CardDescription>The foundation of image regeneration</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                Autoencoders are a type of neural network used to learn efficient representations of data, primarily for
                dimensionality reduction. They consist of two main parts:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Encoder:</strong> Compresses the input data into a lower-dimensional representation (latent
                  space).
                </li>
                <li>
                  <strong>Decoder:</strong> Reconstructs the input data from the compressed representation.
                </li>
                <li>
                  <strong>Training:</strong> The network is trained to minimize the difference between the original
                  input and the reconstructed output.
                </li>
              </ul>
              <p className="mt-4">
                In image regeneration, autoencoders learn to capture the essential features of images, allowing for
                reconstruction and generation of similar images.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Variational Autoencoders (VAE)</CardTitle>
              <CardDescription>Advanced generative models</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                Variational Autoencoders extend the autoencoder concept by adding probabilistic elements, making them
                powerful generative models:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Probabilistic Encoding:</strong> Instead of encoding an input as a single point, VAEs encode
                  it as a distribution in latent space.
                </li>
                <li>
                  <strong>Regularization:</strong> VAEs use a KL divergence term to ensure the latent space has good
                  properties for generation.
                </li>
                <li>
                  <strong>Sampling:</strong> New images can be generated by sampling from the latent space and decoding.
                </li>
              </ul>
              <p className="mt-4">
                VAEs excel at image regeneration because they can generate novel, realistic images by interpolating in
                the continuous latent space.
              </p>
            </CardContent>
          </Card>
        </div>

        <div className="mt-12">
          <Card>
            <CardHeader>
              <CardTitle>Applications of Image Regeneration</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
                <div className="p-4 border rounded-lg">
                  <h3 className="font-medium mb-2">Image Denoising</h3>
                  <p className="text-sm text-muted-foreground">
                    Removing noise from images while preserving important details.
                  </p>
                </div>
                <div className="p-4 border rounded-lg">
                  <h3 className="font-medium mb-2">Image Completion</h3>
                  <p className="text-sm text-muted-foreground">
                    Filling in missing parts of images with plausible content.
                  </p>
                </div>
                <div className="p-4 border rounded-lg">
                  <h3 className="font-medium mb-2">Style Transfer</h3>
                  <p className="text-sm text-muted-foreground">
                    Applying the style of one image to the content of another.
                  </p>
                </div>
                <div className="p-4 border rounded-lg">
                  <h3 className="font-medium mb-2">Super Resolution</h3>
                  <p className="text-sm text-muted-foreground">
                    Enhancing the resolution and quality of low-resolution images.
                  </p>
                </div>
                <div className="p-4 border rounded-lg">
                  <h3 className="font-medium mb-2">Data Augmentation</h3>
                  <p className="text-sm text-muted-foreground">
                    Generating variations of training data for machine learning.
                  </p>
                </div>
                <div className="p-4 border rounded-lg">
                  <h3 className="font-medium mb-2">Creative Content</h3>
                  <p className="text-sm text-muted-foreground">
                    Creating new artistic images based on learned patterns.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
